# Generated by Django 3.2.8 on 2021-10-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Register_id', models.BigIntegerField()),
                ('UserId', models.CharField(max_length=100)),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=300)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Zip', models.IntegerField(blank=True, null=True)),
                ('Company', models.CharField(max_length=300)),
                ('CompanyAddress', models.CharField(max_length=300)),
                ('Phone_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
